USE [LabResultsDb]
GO

/****** Object:  Table [dbo].[AllResults]    Script Date: 10/7/2025 10:53:53 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[AllResults](
	[SampleID] [int] NOT NULL,
	[GroupName] [varchar](40) NULL,
	[Lube] [varchar](30) NOT NULL,
	[EQID] [varchar](22) NOT NULL,
	[Comp] [varchar](30) NOT NULL,
	[Loc] [varchar](30) NOT NULL,
	[Temperature] [float] NULL,
	[Time(M)] [int] NULL,
	[Goodness] [float] NULL,
	[Vis_40] [float] NULL,
	[Vis_100] [float] NULL,
	[AN] [float] NULL,
	[KF] [float] NULL,
	[FTIR_H2O] [float] NULL,
	[Filter_Res] [float] NULL,
	[Fe_std] [float] NULL,
	[Sn_std] [float] NULL,
	[Pb_std] [float] NULL,
	[Al_std] [float] NULL,
	[Zn_std] [float] NULL,
	[Cr_std] [float] NULL,
	[Cu_std] [float] NULL,
	[Yield_Stress] [float] NULL,
	[Su_Max] [float] NULL,
	[Su_Rmp] [float] NULL,
	[Su_Flow] [float] NULL,
	[G_30] [float] NULL,
	[G_100] [float] NULL,
	[FTIR_Anti_ox] [float] NULL,
	[FTIR_Ox] [float] NULL,
	[FTIR_Dilution] [float] NULL,
	[Oil_Content] [float] NULL,
	[Bleed] [float] NULL,
	[RBOT] [float] NULL,
	[TFOUT] [float] NULL,
	[TBN] [float] NULL,
	[Flash_Pt] [float] NULL,
	[FTIR_soot] [float] NULL,
	[FTIR_Anti_Wear] [float] NULL,
	[FTIR_cor_Pro] [float] NULL,
	[FTIR_Mixture] [float] NULL,
	[FTIR_Delta] [float] NULL,
	[str_10s] [float] NULL,
	[str_max] [float] NULL,
	[str_min] [float] NULL,
	[str_rcvry] [float] NULL,
	[Td_0_1_r_s] [float] NULL,
	[Td_100_r_s] [float] NULL,
	[eta*_0_1_r_s] [float] NULL,
	[eta_0_1_r_s] [float] NULL,
	[G_0_1_r_s] [float] NULL,
	[G_1_r_s] [float] NULL,
	[G_10_r_s] [float] NULL,
	[G_100_r_s] [float] NULL,
	[tswp_init] [float] NULL,
	[tswp_final] [float] NULL,
	[G_20a] [float] NULL,
	[G_85] [float] NULL,
	[G_20b] [float] NULL,
	[Cone_Pen] [float] NULL,
	[NLGI] [varchar](30) NULL,
	[drop_pt] [float] NULL,
	[Ni_std] [float] NULL,
	[Ag_std] [float] NULL,
	[Na_std] [float] NULL,
	[Mo_std] [float] NULL,
	[Mg_std] [float] NULL,
	[P_std] [float] NULL,
	[B_std] [float] NULL,
	[Ca_std] [float] NULL,
	[Mn_std] [float] NULL,
	[Ba_std] [float] NULL,
	[Si_std] [float] NULL,
	[H_std] [float] NULL,
	[PC_5_10] [float] NULL,
	[PC_10_15] [float] NULL,
	[PC_15_25] [float] NULL,
	[PC_25_50] [float] NULL,
	[PC_50_100] [float] NULL,
	[PC_100_plus] [float] NULL,
	[NAS] [varchar](2) NULL,
	[Resis] [float] NULL,
	[Chlorides] [float] NULL,
	[Phenol] [float] NULL,
	[Amine] [float] NULL,
	[Friction] [float] NULL,
	[Rust] [float] NULL,
	[Fe_lrg] [float] NULL,
	[Cr_lrg] [float] NULL,
	[Cu_lrg] [float] NULL,
	[Sn_lrg] [float] NULL,
	[Pb_lrg] [float] NULL,
	[Al_lrg] [float] NULL,
	[Ni_lrg] [float] NULL,
	[Ag_lrg] [float] NULL,
	[Zn_lrg] [float] NULL,
	[Na_lrg] [float] NULL,
	[Mo_lrg] [float] NULL,
	[Mg_lrg] [float] NULL,
	[P_lrg] [float] NULL,
	[B_lrg] [float] NULL,
	[Ca_lrg] [float] NULL,
	[Mn_lrg] [float] NULL,
	[Ba_lrg] [float] NULL,
	[Si_lrg] [float] NULL,
	[H_lrg] [float] NULL,
	[DilutionFactor] [int] NULL,
	[NormalRubbing] [real] NULL,
	[SevereWearSliding] [real] NULL,
	[SevereWearFatigue] [real] NULL,
	[CuttingPart] [real] NULL,
	[LaminarPart] [real] NULL,
	[Spheres] [real] NULL,
	[DarkMetalloOde] [real] NULL,
	[RedOde] [real] NULL,
	[CorrosiveWearPart] [real] NULL,
	[NonFerrousMetal] [real] NULL,
	[NonMetallicInorganic] [real] NULL,
	[BirefringentOrganic] [real] NULL,
	[NonMetallicAmorphous] [real] NULL,
	[FrictionPolymers] [real] NULL,
	[Fibers] [real] NULL,
	[Judgment] [real] NULL
) ON [PRIMARY]
GO

