USE [LabResultsDb]
GO

/****** Object:  Table [dbo].[LNFData]    Script Date: 10/7/2025 10:58:58 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LNFData](
	[Site] [varchar](16) NULL,
	[Equipment] [varchar](16) NULL,
	[EquipName] [varchar](16) NULL,
	[EquipModel] [varchar](16) NULL,
	[EquipDesignator] [varchar](16) NULL,
	[EquipSN] [varchar](16) NULL,
	[MajorCommand] [varchar](32) NULL,
	[OperatingActivity] [varchar](32) NULL,
	[Port] [varchar](32) NOT NULL,
	[SampDate] [datetime] NOT NULL,
	[SampOrderSeq] [int] NOT NULL,
	[SampNum] [varchar](12) NOT NULL,
	[ProcDate] [datetime] NOT NULL,
	[ProcTime] [time](7) NOT NULL,
	[SoftwareVer] [varchar](4) NOT NULL,
	[ReservoirCap] [real] NULL,
	[FilterRating] [real] NULL,
	[FluidType] [varchar](32) NULL,
	[WaterLimit] [real] NULL,
	[ISO4Limit] [int] NULL,
	[ISO6Limit] [int] NULL,
	[ISO14Limit] [int] NULL,
	[NASLimit] [int] NULL,
	[NAVAirLimit] [int] NULL,
	[CharnLimit] [int] NULL,
	[HALLimit] [int] NULL,
	[SAELimitGT4] [int] NULL,
	[SAELimitGT6] [int] NULL,
	[SAELimitGT14] [int] NULL,
	[SAELimitGT21] [int] NULL,
	[SAELimitGT38] [int] NULL,
	[SAELimitGT70] [int] NULL,
	[HrsMilesOilChange] [real] NULL,
	[HrsMilesOverhaul] [real] NULL,
	[OilAdded] [real] NULL,
	[OperatingHours] [real] NULL,
	[LNFNum] [int] NULL,
	[OperatorID] [varchar](20) NULL,
	[Notes] [varchar](60) NULL,
	[ConcentrationMult] [bit] NULL,
	[MDiamCum5] [real] NULL,
	[MDiamCum10] [real] NULL,
	[MDiamCum15] [real] NULL,
	[MDiamCum20] [real] NULL,
	[MDiamCum25] [real] NULL,
	[MDiamCum50] [real] NULL,
	[MDiamCum100] [real] NULL,
	[MDiamMaxSize] [real] NULL,
	[MDiamMeanSize] [real] NULL,
	[MDiamStdDev] [real] NULL,
	[ISO4] [int] NULL,
	[ISO6] [int] NULL,
	[ISO14] [int] NULL,
	[NAS] [int] NULL,
	[NAVAIR] [int] NULL,
	[CHARN] [int] NULL,
	[HAL] [int] NULL,
	[SAE] [int] NULL,
	[CDiamCum4] [real] NULL,
	[CDiamCum5] [real] NULL,
	[CDiamCum6] [real] NULL,
	[CDiamCum10] [real] NULL,
	[CDiamCum14] [real] NULL,
	[CDiamCum15] [real] NULL,
	[CDiamCum20] [real] NULL,
	[CDiamCum21] [real] NULL,
	[CDiamCum25] [real] NULL,
	[CDiamCum38] [real] NULL,
	[CDiamCum50] [real] NULL,
	[CDiamCum70] [real] NULL,
	[CDiamCum100] [real] NULL,
	[WaterIndex] [real] NULL,
	[CutCum20] [real] NULL,
	[CutCum25] [real] NULL,
	[CutCum50] [real] NULL,
	[CutCum100] [real] NULL,
	[CutMaxSize] [real] NULL,
	[CutCntMean] [real] NULL,
	[CutCntStdDev] [real] NULL,
	[SlideCum20] [real] NULL,
	[SlideCum25] [real] NULL,
	[SlideCum50] [real] NULL,
	[SlideCum100] [real] NULL,
	[SlideMaxSize] [real] NULL,
	[SlideCntMean] [real] NULL,
	[SlideCntStdDev] [real] NULL,
	[FatCum20] [real] NULL,
	[FatCum25] [real] NULL,
	[FatCum50] [real] NULL,
	[FatCum100] [real] NULL,
	[FatMaxSize] [real] NULL,
	[FatCntMean] [real] NULL,
	[FatCntStdDev] [real] NULL,
	[OxideCum20] [real] NULL,
	[OxideCum25] [real] NULL,
	[OxideCum50] [real] NULL,
	[OxideCum100] [real] NULL,
	[OxideMaxSize] [real] NULL,
	[OxideCntMean] [real] NULL,
	[OxideCntStdDev] [real] NULL,
	[OtherCum20] [real] NULL,
	[OtherCum25] [real] NULL,
	[OtherCum50] [real] NULL,
	[OtherCum100] [real] NULL,
	[OtherMaxSize] [real] NULL,
	[OtherCntMean] [real] NULL,
	[OtherCntStdDev] [real] NULL,
	[Fibers] [real] NULL,
	[UserSize1] [int] NULL,
	[UserCnt1] [int] NULL,
	[UserSize2] [int] NULL,
	[UserCnt2] [int] NULL,
	[UserSize3] [int] NULL,
	[UserCnt3] [int] NULL,
	[UserSize4] [int] NULL,
	[UserCnt4] [int] NULL,
	[UserSize5] [int] NULL,
	[UserCnt5] [int] NULL,
	[UserSize6] [int] NULL,
	[UserCnt6] [int] NULL,
	[SAE4] [int] NULL,
	[SAE6] [int] NULL,
	[SAE14] [int] NULL,
	[SAE21] [int] NULL,
	[SAE38] [int] NULL,
	[SAE70] [int] NULL,
	[SAEmax] [real] NULL,
	[PctSoot] [real] NULL,
	[BSW] [real] NULL,
	[CFD] [real] NULL,
	[GOST] [int] NULL,
	[TotalFerrous] [real] NULL,
	[FerrousMaxDiam] [real] NULL,
	[FerrousMeanDiam] [real] NULL,
	[FerrousDiamStdev] [real] NULL,
	[Ferrous25] [real] NULL,
	[Ferrous38] [real] NULL,
	[Ferrous50] [real] NULL,
	[Ferrous100] [real] NULL,
	[FerrousStatus] [int] NULL,
	[SlidingLimit20] [int] NULL,
	[SlidingLimit25] [int] NULL,
	[SlidingLimit50] [int] NULL,
	[SlidingLimit100] [int] NULL,
	[SlidingLimitTotal] [int] NULL,
	[FatigueLimit20] [int] NULL,
	[FatigueLimit25] [int] NULL,
	[FatigueLimit50] [int] NULL,
	[FatigueLimit100] [int] NULL,
	[FatigueLimitTotal] [int] NULL,
	[CuttingLimit20] [int] NULL,
	[CuttingLimit25] [int] NULL,
	[CuttingLimit50] [int] NULL,
	[CuttingLimit100] [int] NULL,
	[CuttingLimitTotal] [int] NULL,
	[NonMetallicLimit20] [int] NULL,
	[NonMetallicLimit25] [int] NULL,
	[NonMetallicLimit50] [int] NULL,
	[NonMetallicLimit100] [int] NULL,
	[NonMetallicLimitTotal] [int] NULL,
	[SootLimit] [real] NULL,
	[GOSTLimit] [int] NULL,
 CONSTRAINT [PK_SAMPLE] PRIMARY KEY CLUSTERED 
(
	[Port] ASC,
	[SampDate] ASC,
	[SampOrderSeq] ASC,
	[SampNum] ASC,
	[ProcDate] ASC,
	[ProcTime] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

